### ISSUE TITLE
Not working for Android 12

### ISSUE THREAD

**Issue by emeryao** [Looki75/looki75productsansfont#4]
*greate module here and I'm using it all the time*

I recently update my Pixel 4 XL to Android 12 and apply Magisk but this module won't work

after doing some google search it seems that the default font file is not `/system/Roboto-*.ttf` any more

Please check

**Comment by altCK129** [comment]
Works for me perfectly fine might be a rom specific issue , [ScreenshotA12](https://photos.app.goo.gl/6WmtkTActZqZFDq96)

**Comment by emeryao** [comment]
Found a workaround [here](https://forum.xda-developers.com/t/font-magisk-module-google-sans-font-systemlessly.3841067/post-86227323)
